#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if [ -L /etc/runit/runsvdir/default/dwl-config-watch ]; then
            rm -f /etc/runit/runsvdir/default/dwl-config-watch
        fi
        ;;
esac

case "$1" in
    purge)
        rm -f /etc/dwl/config.h
        rmdir /etc/dwl 2>/dev/null || true
        ;;
esac

#DEBHELPER#

exit 0
