name: Build Noctalia

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to build'
        required: true
        type: choice
        options:
          - umbriel
          - noctalia-greeter
          - noctalia
          - xdg-desktop-portal-umbriel

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-package-core.yml
    with:
      package: ${{ inputs.package }}
    secrets: inherit
