name: Build Libraries

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to build'
        required: true
        type: choice
        options:
          - wlroots
          - scenefx
          - xwayland-satellite
          - backports

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-package-core.yml
    with:
      package: ${{ inputs.package }}
    secrets: inherit
