name: Build Window Managers

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to build'
        required: true
        type: choice
        options:
          - swayfx
          - niri
          - mangowc
          - hyprland

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-package-core.yml
    with:
      package: ${{ inputs.package }}
    secrets: inherit
