name: Compiler Debug (Bar)
on:
  workflow_dispatch:
  push:

jobs:
  debug-compilation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: debian:trixie
    steps:
      - name: Setup APT and dependencies
        run: |
          apt-get update
          apt-get install -y git build-essential pkg-config
          echo "deb [trusted=yes] https://ezequielgk.github.io/devuan-depot trixie main" > /etc/apt/sources.list.d/devuan-depot.list
          apt-get update
          apt-get install -y wlroots0.20 wayland-protocols libwayland-dev libxkbcommon-dev libinput-dev libpixman-1-dev libfcft-dev libxcb1-dev libxcb-icccm4-dev libegl-dev libgbm-dev libgles-dev libvulkan-dev liblcms2-dev libseat-dev libdisplay-info-dev libdrm-dev libliftoff-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-render0-dev libxcb-res0-dev libxcb-xfixes0-dev libxcb-errors-dev

      - name: Check Wlr headers
        run: |
          find /usr/include/wlr -name "*foreign_toplevel*" > verify.log || true
          cat verify.log
