name: Compiler Debug (FTM)
on:
  workflow_dispatch:
  push:

jobs:
  debug-compilation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: debian:trixie
    steps:
      - name: Setup APT and dependencies
        run: |
          apt-get update
          apt-get install -y git build-essential pkg-config jq wget foot
          echo "deb [trusted=yes] https://ezequielgk.github.io/devuan-depot trixie main" > /etc/apt/sources.list.d/devuan-depot.list
          apt-get update
          apt-get install -y wlroots0.20 wayland-protocols libwayland-dev libxkbcommon-dev libinput-dev libpixman-1-dev libfcft-dev libxcb1-dev libxcb-icccm4-dev libegl-dev libgbm-dev libgles-dev libvulkan-dev liblcms2-dev libseat-dev libdisplay-info-dev libdrm-dev libliftoff-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-render0-dev libxcb-res0-dev libxcb-xfixes0-dev libxcb-errors-dev

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: patched-ftm

      - name: Set up DWL v0.9 source and Bar patch
        run: |
          git clone --branch v0.9 --depth 1 https://codeberg.org/dwl/dwl.git dwl-test
          cd dwl-test
          git clone --depth 1 https://codeberg.org/dwl/dwl-patches.git ../patches
          git apply --include=drwl.h ../patches/patches/bar/bar.patch || true
          
      - name: Inject patched files
        run: |
          cp dwl-patched/dwl.c dwl-test/dwl.c
          cp dwl-patched/config.def.h dwl-test/config.h
          cp dwl-patched/Makefile dwl-test/Makefile
          mkdir -p dwl-test/protocols
          cp dwl-patched/protocols/wlr-foreign-toplevel-management-unstable-v1.xml dwl-test/protocols/
          
      - name: Compile and Test Headless Render
        run: |
          cd dwl-test
          make > ../make.log 2>&1
          mkdir -p /tmp/xdg && XDG_RUNTIME_DIR=/tmp/xdg WLR_BACKENDS=headless ./dwl -d -s 'foot -e sh -c "echo Hello from Foot; sleep 2" & sleep 3; kill $PPID' > ../dwl-headless-ftm.log 2>&1 || true
          cd ..
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config --global --add safe.directory /__w/devuan-depot/devuan-depot
          git pull origin patched-ftm
          git add dwl-headless-ftm.log
          git commit -m "Upload headless ftm log 3"
          git push origin patched-ftm
