name: Test Compiler
on: [push]
jobs:
  test-compile:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    container: { image: "debian:trixie" }
    steps:
      - name: Setup APT
        run: |
          apt-get update
          apt-get install -y gcc pkg-config git
          echo "deb [trusted=yes] https://ezequielgk.github.io/devuan-depot trixie main" > /etc/apt/sources.list.d/devuan-depot.list
          apt-get update
          apt-get install -y wlroots0.20 wayland-protocols libwayland-dev libxkbcommon-dev libinput-dev libpixman-1-dev libfcft-dev libxcb1-dev libxcb-icccm4-dev libegl-dev libgbm-dev libgles-dev libvulkan-dev liblcms2-dev libseat-dev libdisplay-info-dev libdrm-dev libliftoff-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-render0-dev libxcb-res0-dev libxcb-xfixes0-dev libxcb-errors-dev
      
      - uses: actions/checkout@v4
      
      - name: Try compile
        run: |
          gcc -c test-compile.c $(pkg-config --cflags wlroots-0.20 wayland-server) > gcc-output.log 2>&1 || true
      - name: Upload GCC Output
        uses: actions/upload-artifact@v4
        with:
          name: gcc-output
          path: gcc-output.log
